# -*- coding: utf-8 -*-
"""random.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbYK-DVkkwmFJQXJ_BuuqyClARo70g9J
"""

# Program to generate a random number between 0 and 9

# importing the random module
import random

print(random.randint(0,9))